name: Saludos Automáticos

on: 
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '¡Gracias por crear tu primer issue en este proyecto! 🚀'
          pr-message: '¡Gracias por tu primer pull request! Nuestro equipo lo revisará pronto. 🙌'
          comment-message: '¡Gracias por tu primer comentario! Tu participación es muy valiosa para nosotros. 😊'
