name: Revisión Ortográfica

on:
  pull_request:
    branches: [ main ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rojopolis/spellcheck-github-actions@0.33.1
        with:
          source: "./"
          config_path: ".github/spellcheck.yml"